version: '3.5'
services:
  app:
    container_name: admin_ui
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    command: ["npm", "run", "serve"]
    ports:
      - "1000:8080"

networks:
  default:
    external:
      name: schoolar-network

