mutation UpdateEvent($event: EventInput!) {
  updateEvent(event: $event) {
    id
    interval
    frequency
    room
    subjectId
    userId
    eventTypeId
    startDate
    endDate
    startTime
    endTime
    groupId
    group {
      number
    }
    subject {
      name
    }
    professor {
      name
      surname
      title
    }
    eventType {
      type
      color
    }
  }
}
