export const SET_ERROR = 'SET_ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const GET_EVENT_TYPES = 'GET_EVENT_TYPES';
export const POST_EVENT_TYPE = 'POST_EVENT_TYPE';
export const DELETE_EVENT_TYPE = 'DELETE_EVENT_TYPE';
export const UPDATE_EVENT_TYPE = 'UPDATE_EVENT_TYPE';
