export const SET_ERROR = 'SET_ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const GET_PROFESSORS = 'GET_PROFESSORS';
export const POST_PROFESSOR = 'POST_PROFESSOR';
export const DELETE_PROFESSOR = 'DELETE_PROFESSOR';
export const UPDATE_PROFESSOR = 'UPDATE_PROFESSOR';
